### PR TITLE
fix: adaptive overview level selection

### LINKED ISSUE #567: Overviews: more adaptive level selection
The default 'AUTO' now comes down to using a fixed list, and 'ALL' is mostly the same.

AUTO should generate overviews until the smallest overview image size is smaller than 1024x1024. It should also skip the first, largest, overview level.
ALL should do the same, but also include that first level. 

Use case: generating very large tiffs for data extracts.

### PR DESCRIPTION
**Pull request by dsamaey**

### CODE REVIEW

File: openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala [hunk 1]
```diff
@@ -138,16 +139,14 @@ package object geotiff {
...
-                      formatOptions: GTiffOptions = new GTiffOptions
-                     ): JList[(String, String, Extent)] = {
+                      formatOptions: GTiffOptions = new GTiffOptions,
+                      overviewReductions: (GridBounds[Int], GTiffOptions) => List[Int] = defaultOverviewReductions
+
+  ): JList[(String, String, Extent)] = {
     rdd.sparkContext.setCallSite(s"save_result(GTiff, temporal)")
     formatOptions.assertNoConflicts()
-    val ret = saveRDDTemporalAllowAssetPerBand(rdd, path, zLevel, cropBounds, formatOptions)
+    val ret = saveRDDTemporalAllowAssetPerBandInternal(rdd, path, zLevel, cropBounds, formatOptions, overviewReductionsFunction = overviewReductions)
```
Comment (ElienVandermaesenVITO) [inline openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala:155]:
```suggestion
    val ret = saveRDDTemporalAllowAssetPerBand(rdd, path, zLevel, cropBounds, formatOptions, overviewReductionsFunction = overviewReductions)
```

File: openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala [hunk 2]
```diff
@@ -138,16 +139,14 @@ package object geotiff {
                       path: String,
                       zLevel: Int = 6,
                       cropBounds: Option[Extent] = Option.empty[Extent],
-                      formatOptions: GTiffOptions = new GTiffOptions
-                     ): JList[(String, String, Extent)] = {
+                      formatOptions: GTiffOptions = new GTiffOptions,
+                      overviewReductions: (GridBounds[Int], GTiffOptions) => List[Int] = defaultOverviewReductions
```
Comment (ElienVandermaesenVITO) [inline openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala]:
```suggestion
                      overviewReductions: List[Int],
```

File: openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala [hunk 3]
```diff
@@ -237,13 +245,34 @@ package object geotiff {
...
    */
   //noinspection ScalaWeakerAccess
   def saveRDDTemporalAllowAssetPerBand(rdd: MultibandTileLayerRDD[SpaceTimeKey],
                                        path: String,
                                        zLevel: Int = 6,
                                        cropBounds: Option[Extent] = Option.empty[Extent],
-                                       formatOptions: GTiffOptions = new GTiffOptions
+                                       formatOptions: GTiffOptions = new GTiffOptions,
+                                      ): JList[Item] = {
+    saveRDDTemporalAllowAssetPerBandInternal(rdd, path, zLevel, cropBounds, formatOptions, overviewReductionsFunction=defaultOverviewReductions)
```
Comment (ElienVandermaesenVITO) [inline openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala:265]:
```suggestion
    saveRDDTemporalAllowAssetPerBand(rdd, path, zLevel, cropBounds, formatOptions, overviewReductionsFunction)
```

File: openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala [hunk 4]
```diff
@@ -237,13 +245,34 @@ package object geotiff {
...
+   * Save temporal rdd, on the executors
+   *
+   * @param rdd
+   * @param path
+   * @param zLevel
+   * @param cropBounds
+   * @param formatOptions
+   */
+  //noinspection ScalaWeakerAccess
+  private[geotiff] def saveRDDTemporalAllowAssetPerBandInternal(rdd: MultibandTileLayerRDD[SpaceTimeKey],
```
Comment (ElienVandermaesenVITO) [inline openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala:278]:
```suggestion
  private[geotiff] def saveRDDTemporalAllowAssetPerBand(rdd: MultibandTileLayerRDD[SpaceTimeKey],
```

File: openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala [hunk 5]
```diff
@@ -237,13 +245,34 @@ package object geotiff {
...
+                                       path: String,
+                                       zLevel: Int = 6,
+                                       cropBounds: Option[Extent] = Option.empty[Extent],
+                                       formatOptions: GTiffOptions = new GTiffOptions,
+                                       overviewReductionsFunction: (GridBounds[Int], GTiffOptions) => List[Int] = defaultOverviewReductions
```
Comment (ElienVandermaesenVITO) [inline openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala]:
```suggestion
                                       overviewReductions: List[Int]
```

File: openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala [hunk 6]
```diff
@@ -377,6 +399,34 @@ package object geotiff {
     items.toList.asJava
   }
 
+  private def generateOverviews(formatOptions: GTiffOptions, croppedExtent: Extent, tileLayout: TileLayout, tile: Tile, compressor: Compressor, overviewReductions: List[Int]): List[Array[Byte]] = {
```
Comment (ElienVandermaesenVITO) [inline openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala:418]: The tileSize cant be smaller than 16, this needs to be checked. Now it will give problems

File: openeo-geotrellis/src/test/scala/org/openeo/geotrellis/geotiff/WriteRDDToGeotiffTest.scala [hunk 7]
```diff
@@ -480,7 +506,10 @@ class WriteRDDToGeotiffTest extends RasterMatchers {
 
     def testValues(resampleMethod: String, expectedValues0:Array[Int], expectedValues1:Array[Int],expectedValue2:Int) = {
       options.setResampleMethod(resampleMethod)
-      saveRDDTemporal(layer, outDir.toString, formatOptions = options)
+      def reductionsForTest(gridBounds: GridBounds[Int], options: GTiffOptions): List[Int] = {
+        List(4, 8, 16)
+      }
+      saveRDDTemporal(layer, outDir.toString, formatOptions = options, overviewReductions = reductionsForTest)
```
Comment (ElienVandermaesenVITO) [inline openeo-geotrellis/src/test/scala/org/openeo/geotrellis/geotiff/WriteRDDToGeotiffTest.scala]:
```suggestion
      saveRDDTemporal(layer, outDir.toString, formatOptions = options, overviewReductions = List(4, 8, 16)t)
```

File: openeo-geotrellis/src/test/scala/org/openeo/geotrellis/geotiff/WriteRDDToGeotiffTest.scala [hunk 8]
```diff
@@ -507,8 +536,8 @@ class WriteRDDToGeotiffTest extends RasterMatchers {
 
   @Test
   def testWriteMultibandTemporalRDDWithGapsOverviews(): Unit = {
-    val layoutCols = 8
-    val layoutRows = 4
+    val layoutCols = 18
+    val layoutRows = 14
```
Comment (ElienVandermaesenVITO) [inline openeo-geotrellis/src/test/scala/org/openeo/geotrellis/geotiff/WriteRDDToGeotiffTest.scala]: Why change these?

File: openeo-geotrellis/src/test/scala/org/openeo/geotrellis/geotiff/WriteRDDToGeotiffTest.scala [hunk 9]
```diff
@@ -531,34 +560,10 @@ class WriteRDDToGeotiffTest extends RasterMatchers {
     ) {
       assertEquals(resampled0.get(i,j), overview0.get(i,j))
     }
-    val resampled1 = resampled0.resample(256*layoutCols/8,256*layoutRows/8)
```
Comment (ElienVandermaesenVITO) [inline openeo-geotrellis/src/test/scala/org/openeo/geotrellis/geotiff/WriteRDDToGeotiffTest.scala:534]: Dont delete,

File: openeo-geotrellis/src/test/scala/org/openeo/geotrellis/geotiff/WriteRDDToGeotiffTest.scala [hunk 10]
```diff
@@ -615,9 +620,9 @@ class WriteRDDToGeotiffTest extends RasterMatchers {
   }
 
   @Test
-  def testWriteMultibandTemporalRDDWithGapsSeparateAssetPerBandOverview(): Unit = {
-    val layoutCols = 8
-    val layoutRows = 4
+  def testWriteMultibandTemporalRDDWithGapsSeparateAssetPerBandOverview_ALL(): Unit = {
+    val layoutCols = 18
+    val layoutRows = 14
```
Comment (ElienVandermaesenVITO) [inline openeo-geotrellis/src/test/scala/org/openeo/geotrellis/geotiff/WriteRDDToGeotiffTest.scala:652]: Why change?

File: openeo-geotrellis/src/test/scala/org/openeo/geotrellis/geotiff/WriteRDDToGeotiffTest.scala [hunk 11]
```diff
@@ -630,7 +635,7 @@ class WriteRDDToGeotiffTest extends RasterMatchers {
     options.addBandTag(1, "DESCRIPTION", "B02")
     options.addBandTag(2, "DESCRIPTION", "B03")
     options.setOverview("ALL")
-    val tiles = saveRDDTemporalAllowAssetPerBand(layer, outDir.toString, formatOptions = options)
+    val tiles = saveRDDTemporalAllowAssetPerBandInternal(layer, outDir.toString, formatOptions = options)
```
Comment (ElienVandermaesenVITO) [inline openeo-geotrellis/src/test/scala/org/openeo/geotrellis/geotiff/WriteRDDToGeotiffTest.scala:665]:
```suggestion
    val tiles = saveRDDTemporalAllowAssetPerBand(layer, outDir.toString, formatOptions = options)
```

**Review by ElienVandermaesenVITO — CHANGES_REQUESTED** [review]

File: openeo-geotrellis/src/test/scala/org/openeo/geotrellis/geotiff/WriteRDDToGeotiffTest.scala (hunk 10 above)
Comment (dsamaey) [reply openeo-geotrellis/src/test/scala/org/openeo/geotrellis/geotiff/WriteRDDToGeotiffTest.scala:652]: A bigger area is needed to have multiple overview  levels

File: openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala (hunk 1 above)
Comment (dsamaey) [reply openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala:155]: This ugly "internal" thing stems from :
- Python code calls "Java" code - it can't use the default (Scala) parameter values.
- Scala can't overload methods with optional parameters, hence the different names

File: openeo-geotrellis/src/test/scala/org/openeo/geotrellis/geotiff/WriteRDDToGeotiffTest.scala (hunk 7 above)
Comment (dsamaey) [reply openeo-geotrellis/src/test/scala/org/openeo/geotrellis/geotiff/WriteRDDToGeotiffTest.scala]: I chose to use a function instead of a fixed list.

File: openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala (hunk 1 above)
Comment (ElienVandermaesenVITO) [reply openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala:155]: Do you need the optional parameter?

File: openeo-geotrellis/src/test/scala/org/openeo/geotrellis/geotiff/WriteRDDToGeotiffTest.scala (hunk 7 above)
Comment (ElienVandermaesenVITO) [reply openeo-geotrellis/src/test/scala/org/openeo/geotrellis/geotiff/WriteRDDToGeotiffTest.scala]: Why? This only complicates things
