### PR TITLE
Shub time dimension filter

### LINKED ISSUE #749: `date_between` in temporal `filter_labels` does not work for sentinelhub collections
Using `date_between` in `filter_labels` along temporal dimension does not work.

e.g.

```python
con = openeo.connect("openeo.vito.be")
con.authenticate_oidc()
raw = con.load_collection(
    "SENTINEL2_L2A",
    temporal_extent=["2023-06-01", "2023-09-30"],
    spatial_extent={"west": 4, "south": 51, "east": 4.01, "north": 51.01},
    bands=["B03"]
)
filtered = raw.filter_labels(
    dimension="t",
    condition=lambda data: openeo.processes.date_between(data, min="2023-06-15", max="2023-06-30")
)
filtered.download("filtered.nc")
ds = xarray.load_dataset("filtered.nc")
ds["B03"]["t"]
```
gives 
```
      ['2023-06-04T00:00:00.000000000', '2023-06-09T00:00:00.000000000',
       '2023-06-14T00:00:00.000000000', '2023-06-19T00:00:00.000000000',
       '2023-06-24T00:00:00.000000000', '2023-06-29T00:00:00.000000000',
       '2023-07-04T00:00:00.000000000', '2023-07-09T00:00:00.000000000',
       '2023-07-14T00:00:00.000000000', '2023-07-19T00:00:00.000000000',
       '2023-07-24T00:00:00.000000000', '2023-07-29T00:00:00.000000000', ...
```

while only this is expected:
```
[
       '2023-06-19T00:00:00.000000000',
       '2023-06-24T00:00:00.000000000', '2023-06-29T00:00:00.000000000',
]
```

### PR DESCRIPTION
**Pull request by EmileSonneveld**

### CODE REVIEW

File: geotrellis-sentinelhub/src/main/scala/org/openeo/geotrellissentinelhub/PyramidFactory.scala [hunk 1]
```diff
@@ -233,6 +233,9 @@ class PyramidFactory(collectionId: String, datasetId: String, catalogApi: Catalo
   Seq[(Int, MultibandTileLayerRDD[SpaceTimeKey])] = {
     // TODO: use ProjectedPolygons type
     // TODO: reduce code duplication with pyramid_seq()
+    if (dataCubeParameters.timeDimensionFilter.isDefined) {
+      throw new IllegalArgumentException("OpenEO does not support timeDimensionFilter yet for SentinelHub layers. (Probably used in filter_labels)")
```
Comment (EmileSonneveld) [inline geotrellis-sentinelhub/src/main/scala/org/openeo/geotrellissentinelhub/PyramidFactory.scala:237]: @jdries Error message ok?

Comment (jdries) [reply geotrellis-sentinelhub/src/main/scala/org/openeo/geotrellissentinelhub/PyramidFactory.scala:237]: I don't think user will know what timeDimensionFilter is, and 'layer' is also not a user-facing concept. 
I tend to write errors like:
'filter_labels on time dimension is not supported for sentinelhub collections.'

Comment (EmileSonneveld) [reply geotrellis-sentinelhub/src/main/scala/org/openeo/geotrellissentinelhub/PyramidFactory.scala:237]: Changed: https://github.com/Open-EO/openeo-geotrellis-extensions/commit/0d1025843435f87337111a6ba2406e40e6619676
