### PR TITLE
#670 ClassCastException NetCDFWriter

### LINKED ISSUE #670: NetCDFRDDWriter ClassCastException due to unexpected celltype
I get the following error in the NetCDFRDDWriter when running load_collection for a certain extent in `TERRASCOPE_S2_TOC_V2`, most other extents work:
```
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.openeo.geotrellis.netcdf.NetCDFRDDWriter.writeRasters.
: java.lang.ClassCastException: class [I cannot be cast to class [S ([I and [S are in module java.base of loader 'bootstrap')
	at ucar.nc2.jni.netcdf.Nc4Iosp.writeData(Nc4Iosp.java:3082)
	at ucar.nc2.jni.netcdf.Nc4Iosp.writeData(Nc4Iosp.java:2996)
	at ucar.nc2.NetcdfFileWriter.write(NetcdfFileWriter.java:1066)
	at ucar.nc2.NetcdfFileWriter.write(NetcdfFileWriter.java:1050)
	at org.openeo.geotrellis.netcdf.NetCDFRDDWriter$.writeTile(NetCDFRDDWriter.scala:358)
	at org.openeo.geotrellis.netcdf.NetCDFRDDWriter$.$anonfun$saveSingleNetCDFGeneric$5(NetCDFRDDWriter.scala:265)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:192)
	at org.openeo.geotrellis.netcdf.NetCDFRDDWriter$.$anonfun$saveSingleNetCDFGeneric$3(NetCDFRDDWriter.scala:239)
	at org.openeo.geotrellis.netcdf.NetCDFRDDWriter$.$anonfun$saveSingleNetCDFGeneric$3$adapted(NetCDFRDDWriter.scala:202)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:619)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:617)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1306)
	at org.openeo.geotrellis.netcdf.NetCDFRDDWriter$.saveSingleNetCDFGeneric(NetCDFRDDWriter.scala:202)
	at org.openeo.geotrellis.netcdf.NetCDFRDDWriter$.saveSingleNetCDFGeneric(NetCDFRDDWriter.scala:150)
	at org.openeo.geotrellis.netcdf.NetCDFRDDWriter$.writeRasters(NetCDFRDDWriter.scala:81)
	at org.openeo.geotrellis.netcdf.NetCDFRDDWriter.writeRasters(NetCDFRDDWriter.scala)
```

I first thought this was related to the resolveTileOverlap code in the FileLayerProvider (see https://github.com/eu-cdse/openeo-cdse-infra/issues/956) but currently it happens regardless if this feature flag is on or not. It also happens for both the STAC and the Opensearch version of the collection.

## Job Ids
*  TERRASCOPE_S2_TOC_V2 on mep-prod: j-2603121439314bec8e42145f32d6f9a3
* TERRASCOPE_S2_TOC_V2 on mep-dev: j-2603121413064f66858c381e65bd3a71
* _TERRASCOPE_S2_TOC_V2_OPENSEARCH on mep-dev: j-2603121322264a82b025baf72ef8d244 

## Reproduction
You can reproduce the issue with the following code. The batch job is expected to fail for both collections.
https://gist.github.com/JeroenVerstraelen/d04f0349e5cb2f001a8007f2e0a4365f

## Priority
This issue is currently on production for a very popular layer so this has high priority.

### PR DESCRIPTION
**Pull request by ElienVandermaesenVITO**
#670

### CODE REVIEW

File: openeo-geotrellis/src/main/scala/org/openeo/geotrellis/netcdf/NetCDFRDDWriter.scala [hunk 1]
```diff
@@ -199,9 +199,18 @@ object NetCDFRDDWriter {
       }
     val bandStatistics = collection.mutable.Map[String,(Double,Double,Double,Double,Int,Int)]() // min, max, sum, sum of the power, valid data count, total data count
     var netcdfFile: NetcdfFileWriter = null
+    val cellType = cachedRDD.map(x => x._2.cellType).fold(BitCellType)((x,y)=> {
```
Comment (bossie) [inline openeo-geotrellis/src/main/scala/org/openeo/geotrellis/netcdf/NetCDFRDDWriter.scala]: Is this functionally different from: https://github.com/Open-EO/openeo-geotrellis-extensions/blob/a894f2651637656e54b207b94768be451f1238fb/openeo-geotrellis/src/main/scala/org/openeo/geotrellis/OpenEOProcessScriptBuilder.scala#L85-L103?

Could you move this to a named function?

**Review by bossie — CHANGES_REQUESTED** [review]
Could you add a simple unit test that mimics the minimal process graph from #670?

AFAICT there's no more difference for the `SENTINEL3_SLSTR_L2_LST` process graph so 👍

File: openeo-geotrellis/src/main/scala/org/openeo/geotrellis/netcdf/NetCDFRDDWriter.scala (hunk 1 above)
Comment (ElienVandermaesenVITO) [reply openeo-geotrellis/src/main/scala/org/openeo/geotrellis/netcdf/NetCDFRDDWriter.scala]: For the possible` CellTypes` they will give the same result. The `cellTypeUnion` considers a case where there is an unsigned and a floating point with the same bits, which does not exists. So it is just a different order of checking things

Comment (ElienVandermaesenVITO) [reply openeo-geotrellis/src/main/scala/org/openeo/geotrellis/netcdf/NetCDFRDDWriter.scala]: I'm hoping that geotrellis corrects its union function, so that we can use that one. (see the added comment)

Comment (bossie) [reply openeo-geotrellis/src/main/scala/org/openeo/geotrellis/netcdf/NetCDFRDDWriter.scala]: Ok, but in the meanwhile, can we just keep one implementation then, whichever you think is best?
